---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install zip unzip."
  become: yes
  apt:
    name: ["zip", "unzip"]
    state: latest
    update_cache: yes    

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# - name: Creates directory
#   copy:
#     src:  /root/project/backend/dist/
#     dest: /home/ubuntu/

# - name: Clone a github repository
#   git:
#     repo: https://github.com/bdhakad/cdond-c3-projectstarter.git
#     dest: /home/ubuntu/web
#     clone: yes
#     update: yes        